language: python
python:
  - 2.7
virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get install -qq libatlas3gf-base libatlas-dev
  - pip install --use-mirrors -qq numexpr
  - pip install --use-mirrors -qq pyparsing
  - sudo apt-get update
  - sudo apt-get install -qq python-numpy
  - sudo apt-get install -qq python-scipy
  - sudo apt-get install -qq python-matplotlib
  - sudo apt-get install -qq libhdf5-serial-dev
  - sudo apt-get install -qq libfftw3-dev libfftw3-doc 
  - pip install nose
  - pip install cython
  - pip install tables
  - pip install pyyaml
  - pip install mdtraj
  - pip install simtk.unit
  - pip install fabio
  - git clone --depth 5 https://github.com/hgomersall/pyFFTW.git; cd pyFFTW; python setup.py build_ext --inplace ; sudo python setup.py install ; cd ..
install:
  - python setup.py install
env:
  - TESTFOLDER=test/scatter
  - TESTFOLDER=test/xray/test_xray.py
  - TESTFOLDER=test/xray/test_xray2.py
script: nosetests -v "$TESTFOLDER"
